version: '3'
services:
  app_server:
    container_name: app-server
    build: ./app-server

  http_server:
    container_name: http-server
    build: ./http-server

  web_client:
    container_name: web-client
    build: ./web-client

  database:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=sandbox
      - POSTGRES_USER=sandbox
      - POSTGRES_DB=sandbox
    volumes:
       - ./postgres-data:/var/lib/postgresql/data
